### PR TITLE
Created README.md file for Stacks

### PR DESCRIPTION
**Pull request by debangeedas**

### CODE REVIEW

**Comment by debangeedas** [comment]
Hey! Could you please check my PR out?

**Comment by SiddharthaAnand** [comment]
Reviewing.

**Comment by debangeedas** [comment]
Hey! Is there any problem with the file?

**Comment by debangeedas** [comment]
I hate to be a bother, but I would really appreciate any update on the status

**Comment by debangeedas** [comment]
It is really disappointing when you don't get a response after putting in some effort. I'm sure this wouldn't have taken more than 10 minutes to review. If you do not like the contribution, please be upfront with it. It is better than keeping it hanging.

**Comment by SiddharthaAnand** [comment]
Hey @debangeedas, 

A suggestion. 
- There is a code of conduct which you need to abide by when you are working on an Issue/Open Source Contributions, be it any open-source project. This is a voluntary contribution which should come from within, a feeling based on your interest that you are doing something good for the open-source community because this community thrives on that and that alone.

- Your conduct is of paramount importance while you talk to people in the open source community in such forums, making sure that in no way you show your frustation because of any reason. This is a field where you are probably never going to meet people in person, thus they will get an impression about you by what you speak, the code that you write, and the attitude that you carry when someone critiques it.

- You also need to keep in mind that people here in the open-source community may have other jobs as well to take care of which might delay responses. If you notice the highest rated projects on github also have a high number of PRs in the pending state, which although may take some time to be reviewed but it is reviewed nonetheless.

About the PR:
Don't see any issues with it since this is a simple one!
Merging it :) | Updating the hacktoberfest label as well since I think that is what you are after. Try to think of this as something of a learning rather than getting a t-shirt.

**Comment by debangeedas** [comment]
Thank you sir for the advice. I think you should consider the fact that I had asked for updates and waited for long before I spoke up. Also you responded after I spoke up. I hope you will not take this as aggression but uncertainty. I am sorry if I have been rude.

**Comment by SiddharthaAnand** [comment]
There is always a first time, if that helps. :) 

Don't worry. Be happy!

**P.S. Avoid salutations (sir). Doesn't feel right to me :P**

**Pull request merged**
