### PR TITLE
Added the details for LinkedList Data structure in README.md

### PR DESCRIPTION
**Pull request by KhushalPShah**

### CODE REVIEW

**Comment by SiddharthaAnand** [comment]
Please link this PR to an Issue. Marking this as spam and invalid till then.

**Comment by KhushalPShah** [comment]
This PR is related to the following Issue:
https://github.com/SiddharthaAnand/datastructures/issues/44

**Comment by KhushalPShah** [comment]
Is there something wrong?
Or something I need to change ?
@SiddharthaAnand 
PS : I am new to open source.
Thanks!

**Comment by shubhamprk175** [comment]
@KhushalPShah You might want to add the issue number in your PR's description. You can follow my PR: https://github.com/SiddharthaAnand/datastructures/pull/66

**Comment by KhushalPShah** [comment]
Resolves : #44

**Pull request closed without merging**
